{
  "formatVersion": "1.1",
  "component": {
    "group": "tk.sciwhiz12.gradle",
    "module": "crucible",
    "version": "4.2.0-gradle7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "7ugtzp2l3fbmzdgo47twxkngdm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crucible-4.2.0-gradle7-SNAPSHOT.jar",
          "url": "crucible-4.2.0-gradle7-SNAPSHOT.jar",
          "size": 414770,
          "sha512": "6cf5d05745ac963ad95b6611a07f487fa01f5ee0cb68e5904e3822cbb2a44085fb7688277629707e934e3aea96dee142b322ab596aa64a935543a7b381d30474",
          "sha256": "b710153f440c27a832eff8132d9b329e21c325b636cc74eac7b0394a8f5efe96",
          "sha1": "cd91b2020713485fb77c2719caf1cbfc594b7184",
          "md5": "5c57cc8a1e3d87d9186ba06c4a5c2a52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "2.0.9-gradle7"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.5"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "crucible-4.2.0-gradle7-SNAPSHOT.jar",
          "url": "crucible-4.2.0-gradle7-SNAPSHOT.jar",
          "size": 414770,
          "sha512": "6cf5d05745ac963ad95b6611a07f487fa01f5ee0cb68e5904e3822cbb2a44085fb7688277629707e934e3aea96dee142b322ab596aa64a935543a7b381d30474",
          "sha256": "b710153f440c27a832eff8132d9b329e21c325b636cc74eac7b0394a8f5efe96",
          "sha1": "cd91b2020713485fb77c2719caf1cbfc594b7184",
          "md5": "5c57cc8a1e3d87d9186ba06c4a5c2a52"
        }
      ]
    }
  ]
}
