{
  "formatVersion": "1.1",
  "component": {
    "group": "tk.sciwhiz12.gradle",
    "module": "crucible",
    "version": "4.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "yw5q3vaamfdvjhiwqyyhdctqwa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crucible-4.2.0-SNAPSHOT.jar",
          "url": "crucible-4.2.0-SNAPSHOT.jar",
          "size": 389234,
          "sha512": "e52e2d098df73ee18365cabbaeace470eae41d3ba43706dcd1c4f465ee66e3e81265c4bce47f6a390e319844b28b1fdc553eefd2c33c9debf1545cf1143a8fe2",
          "sha256": "926971636b5fc14bd41f6b0f588ad60ff2f7e70f0a78104a80f0e1f99af50c7a",
          "sha1": "c414a607849d32c410b4a6d946be3325f4ba714c",
          "md5": "7f326f9b365672f1164b6d72c9a4af72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.nothome",
          "module": "javaxdelta",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "2.0.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.5"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "crucible-4.2.0-SNAPSHOT.jar",
          "url": "crucible-4.2.0-SNAPSHOT.jar",
          "size": 389234,
          "sha512": "e52e2d098df73ee18365cabbaeace470eae41d3ba43706dcd1c4f465ee66e3e81265c4bce47f6a390e319844b28b1fdc553eefd2c33c9debf1545cf1143a8fe2",
          "sha256": "926971636b5fc14bd41f6b0f588ad60ff2f7e70f0a78104a80f0e1f99af50c7a",
          "sha1": "c414a607849d32c410b4a6d946be3325f4ba714c",
          "md5": "7f326f9b365672f1164b6d72c9a4af72"
        }
      ]
    }
  ]
}
