{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "artifactural",
    "version": "2.0.9-gradle7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "artifactural-2.0.9-gradle7.jar",
          "url": "artifactural-2.0.9-gradle7.jar",
          "size": 62696,
          "sha512": "bb9f7066074d888ec7f51941103fedab0abeda5081c3b97581bedb99d79c4485370036c1c7872f0335694e10985cc236872476a759dcf421621633e0d5ab396a",
          "sha256": "6854fb2b65e5c28a84b2f22a659e0773dceb26d3d0955a7eb0a145657500eed6",
          "sha1": "427a72a4f2bc98f25b2f43dcd4b39f88f08bbb71",
          "md5": "531dbccdc228258e873ba4584dc8c870"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "artifactural-2.0.9-gradle7.jar",
          "url": "artifactural-2.0.9-gradle7.jar",
          "size": 62696,
          "sha512": "bb9f7066074d888ec7f51941103fedab0abeda5081c3b97581bedb99d79c4485370036c1c7872f0335694e10985cc236872476a759dcf421621633e0d5ab396a",
          "sha256": "6854fb2b65e5c28a84b2f22a659e0773dceb26d3d0955a7eb0a145657500eed6",
          "sha1": "427a72a4f2bc98f25b2f43dcd4b39f88f08bbb71",
          "md5": "531dbccdc228258e873ba4584dc8c870"
        }
      ]
    }
  ]
}
